---
title: "ES 207 HW 4 Alan Cai"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---



#14.3.1.1 Exercises
```{r}
# 1. "\" doesn't work because it will be interpreted as an escape from the character that follows it.
# "\\" doesn't work because that is equivalent to the string "\", but that is the special behavior \ not the literal \.
# "\\\" doesn't work because that is equivalent to the escaped special behavior of the string "\", but of what?  There is nothing to the right of it for it to do the escape thing on.

#2. str_view(x, ""\"'\\\\")

# 3. It will search for 5 character sequences where the five characters are as follows:
# Character one: .
# Character two: any character
# Character three: .
# Character four: any character
# Character five: .
# Represent as a string: \\..\\..\\.
```

#14.3.2.1 Exercises

```{r}
#1. str_view(x, "\\$\\^\\$")
#2.1)
str_view(stringr::words, "^y", match = TRUE)
#2.2)
str_view(stringr::words, "x$", match = TRUE)
#2.3)
str_view(stringr::words, "^...$", match = TRUE)
#2.4)
str_view(stringr::words, "^.......", match = TRUE)

```

#14.3.3.1 Exercises

```{r}
#1.1)
str_view(stringr::words, "^(a|e|i|o|u)", match = TRUE)
#1.2)
str_detect(words, "^[^aeiou]+$")
#1.3)
str_view(stringr::words, "[^e](ed)$", match = TRUE)
#1.4)
str_view(stringr::words, "(ise|ing)$", match = TRUE)
#2.
str_view(stringr::words, "ei", match = TRUE) 
   str_view(stringr::words, "ie", match = TRUE)
#3.
str_view(stringr::words, "q[^u]", match = TRUE) #returns nothing.
#4.
str_view(stringr::words, "our$", match = TRUE) 
#5. "(\d)(\d)(\d)- (\d)(\d)(\d)- (\d)(\d)(\d)(\d)"

```

#14.3.4.1 Exercises

```{r}
# 1. ? - {0, 1}
#    + - {1, }
#    * - {0, }
# 
# 2. 1) Any expression.  .* allows for zero or more of any character expect a newline.
#       2) .+ allows for one or more of any characters expect for a newline.  The \\ is a double escape from } so it is looking for           the literal character }.  Same with \\{ - looking for the literal character {.  So {X} where X can be zero or more of any             character except a newline.
#       3) \d{4} is any four digits.  So any four digits, followed by a -, followed by any 2 digits, followed by a =, followed by any 2       digits.
#       4) \\\\ is a literal \.  So 4 consecutive literal backslashes.
# 
# 3.  1) $[^aeiou]{3}
#     2) [aeiou]{3,}
#     3) (([aeiou])([^aeiou])){2,}
# 
# 4. Yes.

```

#14.3.5.1 Exercises

```{r}
# 1. 1) any four consecutive same characters.
#    2) one character, followed by two of the same character.  This combined thing repeated once.
#    3) any two characters, repeated once. (ABAB)
#    4) any character "X", followed by any character, followed by X again, followed by any character.  This entire thing twice.
#    5) Any character "A" followed by zero or more of any character.  That repeated three times.  All of that preceded by any       character "B".  All of that repeated twice.  All of that preceded by any character "C'.  All of that repeated once.

```


Other questions from homework4.nb.html

#Question 2.
```{r}

# typeof(o3.filelist)
# [1] "list"
# It is a list.
# It contains 7 tibbles, one for each txt. file.
```

#Question 3

```{r}
# library(tidyverse)
# ^This line loads and attaches the tidyverse package. 
# 
# require(readr)
# ^This line loads and attaches the readr package. 
# 
# setwd("OzoneData")
# ^This line sets the working directory to the OzoneData subfolder of the previous working directory.
# 
# o3.filenames <- list.files(pattern = ".txt")
# ^This line labels the entries of the o3.filelist after the txt files in the working directory.
# 
# o3.filelist <- lapply(o3.filenames, read_delim, delim = "|")
# ^This line creates a list, applying the read_delim function (deliminating by the | symbol) to all the files within the working directory (specifically those in o3.filenames).  
# 
# names(o3.filelist) <- gsub(".txt","", o3.filenames)
# ^This line removes ".txt" from the end of the heading names of o3.filelist.
```

#Question 4

```{r}

#First five lines same whether using stringr or grep{base}

#new verison of line six using stringr:
names(o3.filelist) <- gsub(".txt","", o3.filenames)

o3.filenames <- str_replace_all(o3.filenames, ".txt", "")

o3.filenames

```

#Question 5

```{r}
# library(data.table)
# library(tidyverse)
# daily <- o3.filelist %>%
#   rbindlist() %>%
#   group_by(site = as.factor(site), date) %>%
#   summarize(o3 = mean(obs, na.rm = TRUE))
# daily


daily <- o3.filelist
daily_bindlist <- rbindlist(daily)
daily_Groupby <- group_by(daily_bindlist, site = as.factor(site), date)
daily_summary <- summarize(daily_Groupby, o3 = mean(obs, na.rm = TRUE))
daily_summary
```


#Question 6

```{r}
# library(data.table)
# library(tidyverse)
# daily <- o3.filelist %>%
#   rbindlist() %>%
#   group_by(site = as.factor(site), date) %>%
#   summarize(o3 = mean(obs, na.rm = TRUE))


answer <- daily_summary %>%
  mutate(Yr = lubridate::year(date)) %>%
  mutate(month = lubridate::month(date)) %>%
  group_by(Yr, month, site) %>%
  summarize(mean_O3 = mean(o3, na.rm=TRUE))

answer
```

#Question 7

```{r}
#I would take the hourly data and do group_by by hour, and then ummarize mean O3 by hour.


hourly <- o3.filelist %>%
  rbindlist() %>%
  group_by(site = as.factor(site), start_hour) %>%
  summarize(hourlymeano3 = mean(obs, na.rm = TRUE))
hourly

  
```

#Question 8

```{r}

NumSanta <- sum(str_detect(location$"Site Name", "Santa"))
paste(c("The number of site names containing 'Santa' is"), NumSanta)
NumSan <- sum(str_detect(location$"Site Name", "San"))
paste(c("The number of site names containing 'San' is"), NumSan)
paste(c("The number of site names containing 'San' but not 'Santa' is"), NumSan-NumSanta)


```

#Question 9

```{r}
ZipCodes <- location$`Zip Code`
Address <- location$Address
temp <- as.double(str_extract(Address, "^\\d")) #Convert to double so can add values later on

AddressFilter1 <- temp/temp #If valid address, make it = 1.  Otherwise NA.

temp <- as.double(str_extract(ZipCodes, "^\\d{5}")) #Extract zipcode as double.  Otherwise NA.

ZipCodeFilter <- temp/temp #If double, equals 1.  Otherwise NA.

AllFilters <- AddressFilter1 + ZipCodeFilter  #If both filters passed, equals 2.  Otherwise NA.
NotCompleteAddress <- length(AllFilters) - sum(is.na(AllFilters))  #Count total number of entries minus those that are NA.  Results in number of valid addresses.
```

#Question 10

```{r}
#An inner join will subset x to the rows of x with matching values for the key variable in y.  It will return that subset of rows of x adding the columns from y to the exisitng columns of x.  

#An inner join will subset x to the rows of x with matching values for the key variable in y.  It will return that subset of rows of x, and only the columns of x.
```

#Question 11

```{r}

str_which(location$Address, "Address Not Known")
str_which(location, "Location Approximate")
str_which(location$'Zip Code', "\\b..\\b") #incomplete Zip Code (only 2 digits?)

sum(is.na(location$Address))
sum(is.na(location$`Zip Code`))
length(unique(location[is.na(location$Address) | is.na(location$`Zip Code`),]$Site))


```
#Question 12
```{r}
NumMerced <- str_detect(location$"County Name", "Merced")
```
